@startuml
NettyServer -> NettyServerHandler: NettyServerHandler#channelRead(...)

NettyServerHandler -> NettyServer: NettyServer#received(...)

NettyServer --> NettyServer: AbstractPeer#received(...)

NettyServer -> MultiMessageHandler: MultiMessageHandler#received(...)

MultiMessageHandler -> HeartbeatHandler: HeartbeatHandler#received(...)

@enduml